FROM amazoncorretto:11 AS builder
ARG DB_PASSWORD
ARG DB_USERNAME
ARG MONGO_URL
ARG MYSQL_URL
ARG PUBLIC_KEY
WORKDIR /app
COPY .mvn .mvn
COPY src src
COPY mvnw mvnw
COPY pom.xml pom.xml
ENV DB_PASSWORD $DB_PASSWORD
ENV DB_USERNAME $DB_USERNAME
ENV MONGO_URL $MONGO_URL
ENV MYSQL_URL $MYSQL_URL
ENV PUBLIC_KEY $PUBLIC_KEY
RUN ./mvnw clean install

FROM amazoncorretto:11
ARG DB_PASSWORD
ARG DB_USERNAME
ARG MONGO_URL
ARG MYSQL_URL
ARG PUBLIC_KEY
WORKDIR /app
COPY --from=builder /app/target/medicine-reminder-0.0.1-SNAPSHOT.jar app.jar
ENV DB_PASSWORD $DB_PASSWORD
ENV DB_USERNAME $DB_USERNAME
ENV MONGO_URL $MONGO_URL
ENV MYSQL_URL $MYSQL_URL
ENV PUBLIC_KEY $PUBLIC_KEY
CMD java -jar app.jar