version: '3'

services:
  medicine1:
    image: medicine_reminder
    depends_on:
      - mongodb
      - mysql
    restart: always

  medicine2:
    image: medicine_reminder
    depends_on:
      - mongodb
      - mysql
    restart: always

  medicine3:
    image: medicine_reminder
    depends_on:
      - mongodb
      - mysql
    restart: always

  web:
    build:
      context: ./nginx/
      dockerfile: Nginx.Dockerfile
    depends_on:
      - medicine1
      - medicine2
      - medicine3
    ports:
      - 5100:5100
    restart: always

  mongodb:
    image: mongo:6-jammy
    ports:
      - 27017:27017

  mysql:
    image: mysql:8.0
    restart: always
    environment:
        - MYSQL_DATABASE=medicine_reminder
        - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

